config/routes.rb
Rails.application.routes.draw do
  resources :books
  resources :posts
  resources :htmxposts
  # get "items/index"
  # get "items/_form"
  # get "items/_item"
  resources :items# , only: [ :index, :create, :update, :destroy ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "books#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/htmxpost.rb
class Htmxpost < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
    #format.turbo_stream
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.turbo_stream
      #   format.html { redirect_to @book, notice: "Book was successfully created." }
      #   format.json { render :show, status: :created, location: @book }
      # else
      #   format.html { render :new, status: :unprocessable_entity }
      #   format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy!

    respond_to do |format|
      format.html { redirect_to books_path, status: :see_other, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.expect(book: [ :title, :content ])
    end
end

app/controllers/htmxposts_controller.rb
class HtmxpostsController < ApplicationController
  before_action :set_htmxpost, only: %i[ show edit update destroy ]

  # GET /htmxposts or /htmxposts.json
  def index
    @htmxposts = Htmxpost.all
  end

  # GET /htmxposts/1 or /htmxposts/1.json
  def show
  end

  # GET /htmxposts/new
  def new
    @htmxpost = Htmxpost.new
  end

  # GET /htmxposts/1/edit
  def edit
  end

  # POST /htmxposts or /htmxposts.json
  def create
    @htmxpost = Htmxpost.new(htmxpost_params)
    if @htmxpost.save
      render partial: "htmxposts/htmxpost", locals: { htmxpost: @htmxpost }
    else
      render partial: "errors", locals: { errors: @htmxpost.errors.full_messages }
    end
  end


  # PATCH/PUT /htmxposts/1 or /htmxposts/1.json
  def update
    respond_to do |format|
      if @htmxpost.update(htmxpost_params)
        format.html { redirect_to @htmxpost, notice: "Htmxpost was successfully updated." }
        format.json { render :show, status: :ok, location: @htmxpost }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @htmxpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /htmxposts/1 or /htmxposts/1.json
  def destroy
    @htmxpost.destroy!

    respond_to do |format|
      format.html { redirect_to htmxposts_path, status: :see_other, notice: "Htmxpost was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_htmxpost
      @htmxpost = Htmxpost.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def htmxpost_params
      params.expect(htmxpost: [ :title, :body ])
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
    @item = Item.new # For the new item form
  end

  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(dom_id(@item), partial: "show", locals: { item: @item })
      end
      format.html { render :show } # Fallback for non-Turbo requests
    end
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      render turbo_stream: [
        turbo_stream.append(:items, partial: "item", locals: { item: @item }),
        turbo_stream.replace(:new_item, partial: "form", locals: { item: Item.new })
      ]
    else
      render turbo_stream: turbo_stream.replace(:new_item, partial: "form", locals: { item: @item }), status: :unprocessable_entity
    end
  end


  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      render partial: "item", locals: { item: @item }
    else
      render partial: "form", locals: { item: @item }, status: :unprocessable_entity
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    # Turbo will automatically remove the item from the DOM via its data-turbo attributes
    head :ok
  end

  private

  def item_params
    params.require(:item).permit(:name, :description)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
    params[:id] = 1
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.turbo_stream
        # format.html { redirect_to @post, notice: "Post was successfully created." }
        # format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_path, status: :see_other, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.expect(post: [ :title, :body ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/htmxposts_helper.rb
module HtmxpostsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
  <p>
    <strong>Title:</strong>
    <%= book.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= book.content %>
  </p>

</div>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.textarea :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/books/create.turbo_stream.erb
<%= turbo_stream.append :books, @book %>

app/views/books/edit.html.erb
<% content_for :title, "Editing book" %>

<h1>Editing book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Show this book", @book %> |
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Books" %>

<h1>Books</h1>

<div id="books">
  <% @books.each do |book| %>
    <%= render book %>
    <p>
      <%= link_to "Show this book", book_path(book), data: { turbo_frame: "show_book" } %>
    </p>
  <% end %>
</div>

<%= link_to "New book", new_book_path %>

<%= turbo_frame_tag :show_book %>

app/views/books/new.html.erb
<% content_for :title, "New book" %>
<%= turbo_frame_tag :znew_book do %>
<h1>New book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Back to books", books_path %>
</div>
<% end %>

app/views/books/show.html.erb
<p style="color: green"><%= notice %></p>
<%= turbo_frame_tag :show_book do %>

<%= render @book %>

<div>
  <%= link_to "Edit this book", edit_book_path(@book) %> |
  <%= link_to "Back to books", books_path %>

  <%= button_to "Destroy this book", @book, method: :delete %>
</div>

<% end %>

app/views/htmxposts/_form.html.erb
<%= form_with model: htmxpost, local: true do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/htmxposts/_htmxpost.html copy.erb
<div id="<%= dom_id(htmxpost) %>" class="mb-3 p-3 border rounded shadow-sm bg-light">
  <p>
    <strong class="text-primary"><%= htmxpost.title %></strong><br>
    <span class="text-muted"><%= htmxpost.body %></span>
  </p>
  <% if htmxpost.persisted? %>
    <div class="d-flex gap-2">
      <%= link_to "Edit", edit_htmxpost_path(htmxpost), class: "btn btn-warning btn-sm", data: { 
            hx_get: edit_htmxpost_path(htmxpost), 
            hx_target: "##{dom_id(htmxpost)}", 
            hx_swap: "outerHTML" } %>
      <%= link_to "Show Here", htmxpost_path(htmxpost), class: "btn btn-primary btn-sm", data: { 
            hx_get: htmxpost_path(htmxpost), 
            hx_target: "##{dom_id(htmxpost)}", 
            hx_swap: "outerHTML", 
            hx_push: "true" } %>
      <%= link_to "Show Full", htmxpost_path(htmxpost), class: "btn btn-info btn-sm", data: { 
            hx_get: htmxpost_path(htmxpost), 
            hx_target: "#zz", 
            hx_swap: "innerHTML" } %>
      <%= link_to "Delete", htmxpost_path(htmxpost), method: :delete, class: "btn btn-danger btn-sm", data: { 
            hx_delete: htmxpost_path(htmxpost), 
            hx_target: "##{dom_id(htmxpost)}", 
            hx_swap: "delete" } %>
    </div>
  <% else %>
    <em class="text-danger">Unsaved Post</em>
  <% end %>
</div>

app/views/htmxposts/_htmxpost.html.erb
<%# _htmxpost.html.erb %>
<div id="<%= dom_id(htmxpost) %>">
  <p>
    <strong><%= htmxpost.title %></strong><br>
    <%= htmxpost.body %>
  </p>
  <% if htmxpost.persisted? %>
    <%= link_to "Edit", edit_htmxpost_path(htmxpost), data: { hx_get: edit_htmxpost_path(htmxpost), hx_target: "##{dom_id(htmxpost)}", hx_swap: "outerHTML" } %>
    <%= link_to "Show Here", htmxpost_path(htmxpost), data: { hx_get: htmxpost_path(htmxpost), hx_target: "##{dom_id(htmxpost)}", hx_swap: "outerHTML" } %>    
    <%= link_to "Show Full", htmxpost_path(htmxpost), data: { hx_get: htmxpost_path(htmxpost), hx_target: "#zz", hx_swap: "innerHTML" } %>
    <%= link_to "Delete", htmxpost_path(htmxpost), method: :delete, data: { hx_delete: htmxpost_path(htmxpost), hx_target: "##{dom_id(htmxpost)}", hx_swap: "delete" } %>
  <% else %>
    <em>Unsaved Post</em>
  <% end %>
</div>

app/views/htmxposts/edit.html.erb
from edit (not form)
<%= form_with model: @htmxpost, data: { hx_patch: htmxpost_path(@htmxpost), hx_target: "##{dom_id(@htmxpost)}", hx_swap: "outerHTML" } do |form| %>
  <div>
    <%= form.text_field :title, value: @htmxpost.title %>
  </div>
  <div>
    <%= form.text_area :content, value: @htmxpost.body %>
  </div>
  <div>
    <%= form.submit "Save" %>
  </div>
<% end %>

app/views/htmxposts/index.html.erb
<%# app/views/htmxposts/index.html.erb %>
<div id="zz"></div>
<h1>HtmxPosts</h1>

<div id="posts">
  <%= render @htmxposts %>
</div>

<div id="new-post-form">
  <%= link_to "New Post", new_htmxpost_path, data: { hx_get: new_htmxpost_path, hx_target: '#new-post-form', hx_swap: 'innerHTML' } %>
</div>

app/views/htmxposts/new.html.erb
<h2>New HtmxPost</h2>

<%= form_with model: @htmxpost, data: { hx_post: htmxposts_path, hx_target: '#posts', hx_swap: 'beforeend' } do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/htmxposts/show.html.erb
<h2>HtmxPost Details</h2>

<div>
  <strong>Title:</strong> <%= @htmxpost.title %><br>
  <strong>Content:</strong> <%= @htmxpost.body %>
</div>

<%= link_to "Back", htmxposts_path, data: { hx_get: htmxposts_path, hx_target: "#posts", hx_swap: "innerHTML", hx_push: "true" } %>

app/views/items/_form.html.erb
<%= form_with model: item, local: false do |f| %>
  <% if item.errors.any? %>
    <% item.errors.full_messages.each do |message|%>
      <%= message %>
    <% end %>
  <% end %>

  <%= f.label :name %><br>
  <%= f.text_field :name %><br>

  <%= f.label :description %><br>
  <%= f.text_field :description %><br>

  <%= f.submit %>
<% end %>

app/views/items/_item.html.erb
<%= turbo_frame_tag dom_id(item) do %>
  <p>
    <strong>Name:</strong>
    <%= link_to item.name, item_path(item), data: { turbo_frame: dom_id(item) } %>
  </p>
  <p>
    <strong>Description:</strong>
    <%= item.description %>
  </p>

  <%= button_to 'Delete', item_path(item), method: :delete, data: { turbo_confirm: 'Are you sure?' } %>
<% end %>

app/views/items/_show.html.erb
<%= turbo_frame_tag dom_id(item) do %>
  <h3><%= item.name %><%= item.name %><%= item.name %></h3>
  <p><strong>Description:</strong> <%= item.description %></p>
  <p><strong>Created At:</strong> <%= item.created_at.strftime("%B %d, %Y") %></p>

  <%= link_to 'Back', items_path, data: { turbo_frame: "items" } %>
<% end %>

app/views/items/index.html.erb
<h1>Items</h1>
<h2>Create Item:</h2>
<div id="new_item_form">
  <%= turbo_frame_tag :new_item do %>
    <%= render 'form', item: @item %>
  <% end %>
</div>

<h2>All Items</h2>
<div id="items">
  <%= turbo_frame_tag :items do %>
    <%= render @items %>
  <% end %>
</div>

app/views/items/show.html.erb
<%= turbo_frame_tag dom_id(item) do %>
  <h3><%= item.name %><%= item.name %><%= item.name %></h3>
  <p><strong>Description:</strong> <%= item.description %></p>
  <p><strong>Created At:</strong> <%= item.created_at.strftime("%B %d, %Y") %></p>

  <%= link_to 'Back', items_path, data: { turbo_frame: "items" } %>
<% end %>

app/views/items/show.turbo_stream.erb
<%= turbo_stream.replace dom_id(@item) do %>
  <%= render partial: "show", locals: { item: @item } %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Turbo Play" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%#= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"  %>    
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'https://unpkg.com/htmx.org/dist/htmx.min.js' %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <script src="https://unpkg.com/htmx.org@1.9.5" integrity="sha384-xcuj3WpfgjlKF+FXhSQFQ0ZNr39ln+hwjN3npfM9VBnUskLolQAcN80McRIVOPuO" crossorigin="anonymous"></script>  
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>      
  </head>

  <body>
    <%= yield %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/_form.html copy.erb
<%= turbo_frame_tag :znew_post do %>
  <%= form_with(model: post) do |form| %>
    <% if post.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
          <% post.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.label :title, style: "display: block" %>
      <%= form.text_field :title %>
    </div>

    <div>
      <%= form.label :body, style: "display: block" %>
      <%= form.textarea :body %>
    </div>

    <div>
      <%= form.submit %>
    </div>
  <% end %>

<% end %>

app/views/posts/_form.html.erb
<%= turbo_frame_tag :znew_post do %>
  <%= form_with(model: post) do |form| %>
    <% if post.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
          <% post.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.label :title, style: "display: block" %>
      <%= form.text_field :title %>
    </div>

    <div>
      <%= form.label :body, style: "display: block" %>
      <%= form.textarea :body %>
    </div>

    <div>
      <%= form.submit %>
    </div>
  <% end %>

<% end %>

app/views/posts/_post.html copy 2.erb
<% frame_id = dom_id(post, "title_turbo_frame") %>
<%= form_with model: post, data: { turbo_frame: frame_id } do %>
  <%= turbo_frame_tag frame_id do %>
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>
    <%= link_to "Edit this post", edit_post_path(post) %> |
<% end %>
<% end %>

<% frame_id = dom_id(post, "body_turbo_frame") %>
<%= form_with model: post, data: { turbo_frame: frame_id } do %>
  <%= turbo_frame_tag frame_id do %>
  <p>
    <strong>Body:</strong>
    <%= post.body %>
  </p>
    <%= link_to "Edit this post", edit_post_path(post) %> |
<% end %>
<% end %>






  <%= button_to "Destroy this post", post, method: :delete %>  

app/views/posts/_post.html copy.erb
<%= turbo_frame_tag :new_post do %>
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= post.body %>
  </p>

  <%= button_to "Destroy this post", post, method: :delete %>  

<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= post.body %>
  </p>

  <%= button_to "Destroy this post", post, method: :delete %>  

</div>

app/views/posts/create.turbo_stream.erb
<%= turbo_stream.append :posts, @post %>
<%= turbo_stream.replace :new_post, partial: 'form', locals: { post: Post.new } %>

app/views/posts/edit.html.erb
<% content_for :title, "Editing post" %>

<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html copy 2.erb
<%# app/views/posts/index.html.erb %>
<p style="color: green"><%= notice %></p>

<% content_for :title, "Posts" %>

<h1>Posts</h1>

<%= params[:id].inspect %>
<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post_path(id: post.id) %>
    </p>
  <% end %>
</div>

<%= turbo_frame_tag :new_post %> <%# , src:new_post_path %>

<%= link_to "New post", new_post_path, data: { turbo_frame: :new_post } %>

app/views/posts/index.html copy 3.erb
<%# app/views/posts/index.html.erb %>
<p style="color: green"><%= notice %></p>

<% content_for :title, "Posts" %>

<h1>Posts</h1>

<%= params[:id].inspect %>
<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post_path(id: post.id) %>
    </p>
  <% end %>
</div>

<%#= turbo_frame_tag :new_post %> <%# , src:new_post_path %>

<!-- Modal Structure -->
<div class="modal fade" id="newPostModal" tabindex="-1" aria-labelledby="newPostModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="newPostModalLabel">New Post</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= turbo_frame_tag :new_post %>
      </div>
    </div>
  </div>
</div>

<!-- Trigger Button -->
<%= link_to "New post", new_post_path, data: { turbo_frame: :new_post, bs_toggle: "modal", bs_target: "#newPostModal" } %>

<%= link_to "New post", new_post_path, data: { turbo_frame: :new_post } %>


<script>
document.addEventListener("turbo:frame-load", (event) => {
  if (event.target.id === "new_post") {
    const modal = new bootstrap.Modal(document.getElementById("newPostModal"));
    modal.show();
  }
});

</script>

app/views/posts/index.html copy.erb
<%# app/views/posts/index.html.erb %>
<p style="color: green"><%= notice %></p>

<% content_for :title, "Posts" %>

<h1>Posts</h1>

<%= params[:id].inspect %>
<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post_path(id: post.id) %>
    </p>
  <% end %>
</div>

<%#= turbo_frame_tag :new_post %> <%# , src:new_post_path %>

<!-- Modal Structure -->
<div class="modal fade" id="newPostModal" tabindex="-1" aria-labelledby="newPostModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="newPostModalLabel">New Post</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= turbo_frame_tag :new_post %>
      </div>
    </div>
  </div>
</div>

<!-- Trigger Button -->
<%= link_to "New post", new_post_path, data: { turbo_frame: :new_post, bs_toggle: "modal", bs_target: "#newPostModal" } %>

<%= link_to "New post", new_post_path, data: { turbo_frame: :new_post } %>


<script>
document.addEventListener("turbo:frame-load", (event) => {
  if (event.target.id === "new_post") {
    const modal = new bootstrap.Modal(document.getElementById("newPostModal"));
    modal.show();
  }
});

</script>

app/views/posts/index.html.erb
<%# app/views/posts/index.html.erb %>
<p style="color: green"><%= notice %></p>

<% content_for :title, "Posts" %>

<h1>Posts</h1>

<%= params[:id].inspect %>
<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post_path(id: post.id) %>
    </p>
  <% end %>
</div>

<%= turbo_frame_tag :new_post, src:post_path(1) %>
<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<% content_for :title, "New post" %>
<%= turbo_frame_tag :new_post do %>
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>
<% end %>

app/views/posts/show.html.erb
<%# app/views/posts/show.html.erb %>
<p style="color: green"><%= notice %></p>
<%= turbo_frame_tag :show_post do %>
<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%#= button_to "Destroy this post", @post, method: :delete %>
</div>
<% end %>

app/views/posts/show.turbo_stream.erb
<%= turbo_stream.append :post_container, @post %>